### ISSUE TITLE
Avoid calling private methods with `.send`

### ISSUE THREAD

**Issue by schnika** [tomdalling/pure-function-as-an-object#2]
I like your whole approach and the way you structure your code. 
There is only one thing that hurts me a bit. In `.convert` you call `#send(:xml)`. With this you 'cheat' on your own implementation. 
To get around this you could call `#xml` in your initializer. I don't know whether this is the right solution to the problem though :)

I would love to hear about your thoughts regarding this topic.

**Comment by tomdalling** [comment]
I don't think it's "cheating," since the class is calling one of its own methods. You can't call `#xml` from within `#initialize` unfortunately, because the return value of `#initialize` is ignored. The other option is to just make the `#xml` method public.

**Comment by schnika** [comment]
Thanks for the feedback :). I wasn't sure about that and wanted to ask.
